swagger: '2.0'
info:
  description: >-
    This is a sample server Petstore server.  You can find out more about    
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/).      For this sample, you can use the api
    key `special-key` to test the authorization     filters.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: petstore.swagger.io
basePath: /v2
tags:
  - name: simulations
    description: Operations around simulations
    externalDocs:
      description: Find out more about simulations
      url: 'http://cropsinsilico.org/'
schemes:
  - http
paths:
  /simulations:
    post:
      tags:
        - simulations
      summary: Add a new simulation data point
      description: ''
      operationId: addSimData
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Simulation data that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Simulation'
      responses:
        '400':
          description: Invalid input
      security:
        - simstore_auth:
            - 'write:simulation'
            - 'read:simulation'
securityDefinitions:
  simstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:simulation': modify simulations in your account
      'read:simulation': read your simulations
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Simulation:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
